export const blue = '#188CD8'
export const lightblue = '#1C9BEF'
export const darkgray = '#526471'
export const mediumgray = '#d0d9df'
export const lightgray = '#d3dbe1'
export const black = '#000'
export const white = '#fff'
